### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Poonam1607**

### CODE REVIEW

**Comment by Poonam1607** [comment]
Now is it okay? @gabrysia694

**Review by gabrysia694 — APPROVED** [review]
Looks good!

**Review by gabrysia694 — APPROVED** [review]

**Comment by Poonam1607** [comment]
> Looks good!

Do I merge pull request?

**Comment by gabrysia694** [comment]
> > Looks good!
> 
> Do I merge pull request?

Create a new pull request containing your code to the main branch, so that I can merge it

**Pull request closed without merging**
